### ISSUE TITLE
New JK-BMS JK-PB2A16S20P  Inverter BMS not yet supported? 

### ISSUE THREAD

**Issue by pos-ei-don** [Louisvdw/dbus-serialbattery#1060]
### Is your feature request related to a problem? Please describe.

Analoge to the other issue, the New Inverter BMS from JK-BMS does not seem to be supported.
I can connect it via USB to Rs485 cable and the jk Software, but nö luck with this driver.
This bms is interesting because it Supports active balancing an the "inverter Features" to Limit the current for example while balancing two different Packs.

If i can help, please just let me know.
I can give ssh access if helpful.

**Comment by mr-manuel** [comment]
It's a bit tricky with the new JK Inverter BMS, since it's still under development from what I understood. Shouldn't it work out of the box with the Victron system? Or do you want to have more details like all the cell voltages?

I reference also this discussion here. https://github.com/Louisvdw/dbus-serialbattery/discussions/969
