### ISSUE TITLE
0.11beta1 and 011beta4 reads wrong cell voltage with Daly-BMS

### ISSUE THREAD

**Issue by centro-max** [Louisvdw/dbus-serialbattery#125]
**Describe the bug**
0.11beta1 reads wrong cell voltage

The fill level, the total voltage and the current [A] are read out correctly, only the minimum and maximum cell voltage in the detail page is incorrect.

I tested it with 2 different Daly-BMS, sometimes the minimum, sometimes and/or the maximum of the cell voltage is wrong.

**VenusOS (please complete the following information):**
 - Raspberry Pi 4b
 - Firmware Version 2.85

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: Daly Smart BMS 100A 16S LifePo4
 - Cells: 16
 - Interface: USB-RS485
![BMS-Fehler](https://user-images.githubusercontent.com/93882970/169681880-df9ce9f0-ae39-4171-8eb2-fe81c4cb2f1a.JPG)
![BMS-Fehler-2](https://user-images.githubusercontent.com/93882970/169681884-6fefbb53-4656-4afe-9fa7-fe745ad8e568.JPG)

**Comment by YoBnEb** [comment]
Hi,
I have quite the same issue while using the 0.11 beta versions. Tried it also with the latest beta 4.
As you can see, the first 7 cell values are correct. Number 8 is the far too low and for cell 9 to 16 there are no values at all.
Running the Daly 16S-200A (version with fan) serialbattery is running on the MP-II 48/3000 GX.


![Daly_Cells](https://user-images.githubusercontent.com/3219566/173440239-43fda79c-e834-436d-9f92-c513ae0f6c0d.png)

Any idea what to check?

Thanks in advance!

By the way... Very nice project :-)

**Comment by towatai** [comment]
Same Problem here on my Rasperry Pi 3 b+ with OS 2.73, Beta4 Driver and my 8S Battery. You can Chek the Values here:
https://vrm.victronenergy.com/installation/175068/share/037bcec3

**Comment by centro-max** [comment]
Same problem with OS 2.87 and beta4. But first time, i can see both bms with OS > 2.73, that ist fine.

![2-87-beta4-1](https://user-images.githubusercontent.com/93882970/173819495-fb8bc4c0-1b53-4c33-aaeb-e5b3a72a8ca1.JPG)
![2-87-beta4-2](https://user-images.githubusercontent.com/93882970/173819500-6349e8ab-99df-4c51-9197-63d3898740d4.JPG)
![2-87-beta4-0](https://user-images.githubusercontent.com/93882970/173819501-f6069229-965e-4e46-a33e-8dccdf3abf66.JPG)

**Comment by Louisvdw** [comment]
Please test if this daly.py solves the min/max cell voltage issue. I think it has to do with the reading of the cell values which is not correct. This then override the min_cell_voltage/max_cell_voltage that is read from the BMS. This this version I have disabled the cell values so that the min/max would be used again. 
I don't have a Daly BMS to test with, so someone will need to test this for me please.

Download this txt file and rename to daly.py and copy to the GX device overriding the existing one (to be replaced over 0.11beta4 build) on /data/etc/dbus-serialbattery/daly.py
Let me know if this works so that I can apply it to the next release.

[daly.txt](https://github.com/Louisvdw/dbus-serialbattery/files/8911190/daly.txt)

**Comment by centro-max** [comment]
Yes it works now! Everything is fine, the min and max Voltage is correct with the new daly.txt file.
OS 2.97, 011beta4, raspberrypi4b, 2 Daly-BMS

**Comment by YoBnEb** [comment]
I can also confirm that the min/max cell values seems to be correct again.
The single cell voltages are gone (as maybe expected...).

**Comment by Louisvdw** [comment]
Thank you for the feedback.
I have made the new release v0.12 which includes the fix
