### ISSUE TITLE
installed capacity displays 50Ah

### ISSUE THREAD

**Issue by josmeijer** [Louisvdw/dbus-serialbattery#596]
![50ah](https://user-images.githubusercontent.com/35534038/235338444-c6596f6a-369f-4173-9863-646d201c9e89.jpg)
![230ah1](https://user-images.githubusercontent.com/35534038/235338765-5a1252d2-ac86-42f9-a7e9-a2e4330f83bc.jpg)
![Screenshot_20230430_081339_com inuker bluetooth daliy](https://user-images.githubusercontent.com/35534038/235338795-9dbadd67-704b-4ed4-aba1-e3916e8efe89.jpg)
 
bug is not the right word, I would say inconvenience or "something that puzzles me"
I ran through all possible parameters (I could find) but I see no way to tell the d-bus serialbattery driver that I have a 230Ah battery bank installed. It is apparently properly installed in both BMS and GX
The available capacity does match reality though.

**Comment by mr-manuel** [comment]
Did you saw the template for a new issue? If not please fill it out and explain shortly how you opened the issue, so we can improve the workflow. If yes there is a reason why we need this data to help you :-)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Venus OS (please complete the following information):**
 - Device type: [e.g. VenusGX, Cerbo, Raspberry Pi]
 - Firmware Version [e.g. 262]

**dbus-serialbattery**
 - Version: [e.g. v0.14.3]

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: [e.g. LTT, Daly]
 - Cells: [e.g. 16]
 - Interface: [e.g. USB-RS485, USB-RS232, Ve.Direct]

**Additional context**
Add any other context about the problem here.

**Comment by towatai** [comment]
You have to Change the Capacity-Size in the config.default.ini from 50 to 230.

; -- Daly settings
; Battery capacity (amps) if the BMS does not support reading it
BATTERY_CAPACITY = 230

**Comment by mr-manuel** [comment]
If it's a Daly, then this is solved. With the published beta, also the capacity from the Daly are read from the BMS.

**Comment by josmeijer** [comment]
a little late, but does this imply I should reinstall the latest version of the driver (or manually change the value)?

**Comment by mr-manuel** [comment]
In the meanwhile a lot changed. I would recommend you to use latest Venus OS with latest driver version.

**Comment by josmeijer** [comment]
I have auto-update on in the CCGX anyway. I'll give the "install from SD" another chance, hopefully that functioning is one of the many changes :-)

**Comment by mr-manuel** [comment]
Why aren't you updating over SSH?

**Comment by josmeijer** [comment]
I was curious whether the new firmware would have solved the ability to
install from SD card (it didn't work on the 0.nn version).
And it is very easy on the CCGX as there is a micro SD slot on the front.
I did all the other adjustments via SSH though.

Op zo 18 jun. 2023 10:59 schreef Manuel ***@***.***>:
